config/routes.rb
Rails.application.routes.draw do
  resources :products
  resources :categories
  #get 'welcome/index'
  
  devise_for :users
  get 'vendedor/index'
  # get 'home/index'
  get '/home', to: "home#index"
  get '/welcome', to: "welcome#index"
  # Defines the root path route ("/")
  root "welcome#index"

=begin
  unauthenticated do
    root :to => 'welcome#index'
  end

  authenticated do
    root :to => 'home#index'
  end
  end
=end
end

app/models/vendedor.rb
class Vendedor < ApplicationRecord
    #vendedor -> representacion de la tabla vendedors en rails
    include PgSearch::Model
    pg_search_scope :search_full_text,
        against: {
        nombre: 'A',
        email: 'B',
        number: 'c',
        }
end

app/controllers/vendedor_controller.rb
class VendedorController < ApplicationController
  def index
    if !user_signed_in?
      redirect_to "/welcome"
    
    else
    #@pagy, @records = pagy(Product.all)
    @pagy, @vendedores = pagy(Vendedor.all)
    
    if params[:query_text].present?
      @vendedores = @vendedores.search_full_text(params[:query_text])
      end     
  end
end

app/helpers/vendedor_helper.rb
module VendedorHelper
end

app/views/vendedor/index.html.erb
<!-- filtro -->
<!--
<form method="get" action="vendedor/index">
    <label for="vendedor"> vendedores </label>
    <input type="text" name="query_text" id="vendedor">

    <input type="submit" value="Buscar">

</form>-->

<%= form_with url: vendedor_index_path, method: :get do |form|%>
    <%= form.text_field :query_text, value: params[:query_text]%>
   <%end%>

<br>
<hr>
<h1>Gestion de Vendedores</h1>
<table>
    <thead>
        <tr>
            <th>id</th>
            <th>Number</th>
            <th>Name</th>
            <th>Email</th>
            <th>Manager</th>
            <th>Oficina</th>
            <th>Acciones</th>
        </tr>
    </thead>
    <tbody>
    <% @vendedores.each do |vendedor|%>
        <tr>
            <td><%= vendedor.id %></td>
            <td><%= vendedor.number %></td>
            <td><%= vendedor.nombre %></td>
            <td><%= vendedor.email%></td>
            <td><%= vendedor.manager %></td>
            <td><%= vendedor.oficina %></td>
            <td></td>
        </tr>
    <%end%>
        <%== pagy_nav(@pagy) if @pagy.pages > 1 %>
    </tbody>
</table>
<%== pagy_nav(@pagy) if @pagy.pages > 1 %>